### ISSUE TITLE
Recommended Nginx Configuration for ZenCache

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache-kb#91]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs
- [x] Update Redirect with published link when live: https://zencache.com/wp-admin/post.php?post=1597&action=edit

---
### KB Article Published @ zencache.com<br />:page_with_curl: See: [Recommended Nginx Configuration for ZenCache](http://zencache.com/kb-article/recommended-nginx-configuration-for-zencache/)

[:octocat: View Markdown File](https://github.com/websharks/zencache-kb/blob/master/tutorials/2015/91-recommended-nginx-configuration-for-zencache.md) | [:pencil2: Edit Markdown File](https://github.com/websharks/zencache-kb/edit/master/tutorials/2015/91-recommended-nginx-configuration-for-zencache.md)

---

**Comment by raamdev** [comment]
Referencing https://github.com/websharks/zencache/issues/427

**Comment by jaswsinc** [comment]
## Suggested Nginx Configuration for ZenCache

```nginx
server {
  etag on;
  expires 7d;
  if_modified_since before;

  gzip on;
  gzip_vary on;
  gzip_comp_level 6;
  gzip_types text/plain text/xml image/svg+xml # text/html in core already.
    application/rss+xml application/atom+xml application/xhtml+xml
    text/css application/json application/x-javascript
    application/font-otf application/font-ttf;

  location ~* \.(?:ttf|ttc|otf|eot|woff|woff2|css|js)$ {
      add_header Access-Control-Allow-Origin *;
  }
}
```

See also, my full example here: https://github.com/jaswsinc/vagrant-ubuntu-lemp/blob/master/assets/nginx/.conf

**Comment by raamdev** [comment]
@jaswsinc Thanks! Do you think you could comment that snippet to explain what each section is for or why we recommend that for ZenCache?

**Comment by jaswsinc** [comment]
```nginx
server {
  etag on;
  expires 7d;
  if_modified_since before;

# ↑ See: http://nginx.org/en/docs/http/ngx_http_core_module.html#etag
# This reduces load on your server by supporting the If-Modified-Since header since by browsers for static resources.

  gzip on;
  gzip_vary on;
  gzip_comp_level 6;
  gzip_types text/plain text/xml image/svg+xml # text/html in core already.
    application/rss+xml application/atom+xml application/xhtml+xml
    text/css application/json application/x-javascript
    application/font-otf application/font-ttf;

# ↑ See: http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip
# This enables GZIP compression in Nginx, making all static resources load faster in browsers.

  location ~* \.(?:ttf|ttc|otf|eot|woff|woff2|css|js)$ {
      add_header Access-Control-Allow-Origin *;
  }

# ↑ See: http://davidwalsh.name/cdn-fonts
# This prevents cross-domain security issues related to fonts. Only needed if you use Static CDN Filters in ZenCache.
}
```

**Comment by raamdev** [comment]
Perfect! Thank you.

**Comment by jaswsinc** [comment]
I added the following note in the draft above...

---

_**Important Note:** The `server{}` configuration block in this example is incomplete; i.e., it only contains the configuration relevant to improving speed on your site and for the best compatibility with ZenCache. It does not include things like `listen` and `try_files` directives. Please consult the [Nginx documentation](http://nginx.org/en/docs/) if you need help with that part._

**Comment by pkiula** [comment]
There should be a way to do this without "if" conditions, which are considered poor in the nginx world.

**Comment by raamdev** [comment]
@pkiula thank you for the feedback. That does look a lot cleaner to me. 

@jaswsinc any objection to the above change?

**Comment by jaswsinc** [comment]
> location ~ (wp\-content/cache/comet\-cache/)$ {
>         return 403;
>       }

This contains an unnecessary `(capture)` and is a caSe-sensitive match. It also contains `$` which would cause it _not_ to match _any_ file location inside the directory.

Also, it appears the intention in this attempt is to guard the entire `comet-cache` directory, which is doesn't do (given the `$`), but if it did, that would prevent public access to JS/CSS files created by the HTML Compressor; i.e., the only private directories are `comet-cache/cache` and `comet-cache/htmlc/private`. The others should remain public or you'll have trouble.

> @jaswsinc any objection to the above change?

Yes. I used `if ($uri ... ` because it is more explicit than `location`, which is also subjected to a [number of rules](http://nginx.org/en/docs/http/ngx_http_core_module.html#location); i.e., using `location`, while not likely, _may_, in unexpected scenarios, result in public access to the cache directory — just depending on the other Nginx configuration lines that a developer has. This is because there is only one `location` selected by Nginx for each request. One of them has to win.

Whereas `if` is not subjected to all of those same rules. In particular, `if` would not get bypassed if someone used the `^~` or `=` modifiers in an unexpected way. Of if another regex pattern were given more weight; which again, could result in public access to the cache directory.

_**Note:** In the world of Nginx, `if` [has been described](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/) as being 'evil'. However, as the article states, so long as `if` is _not_ used inside a `location{}` block, [`if` is not evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/) whatsoever. In short, I agree that `if`, in the world of Nginx, is bad, generally speaking. But there are legitimate use cases, and so long as you're using it correctly there's not a problem._

---

### Using `location {}`

All of that said, it's OK to use `location`. Just be sure to get it right and position it accordingly; i.e., alongside whatever other rules that you have. If your `nginx.conf` contains any tricky `location { location {} }` nesting, be sure to position this in a way that gives it the highest priority, and don't forget about internal redirects that can occur when `try_files` is used.

_As long as you're not doing anything tricky, this will do just fine._

```nginx
location ~* /wp\-content/cache/comet\-cache/cache(?:/|$) {
  return 403;
}
location ~* /wp\-content/cache/comet\-cache/htmlc/private(?:/|$) {
  return 403;
}
```

---

Or you can stick with `if` and just put these anywhere in your `server{}` block, which covers everything that you serve, regardless of which `location` is selected by Nginx; i.e., `if` will always deny access as expected; i.e., it's explicitly checking the `$uri` for a match in every request.

```nginx
if ($uri ~* /wp\-content/cache/comet\-cache/cache(?:/|$)) {
  return 403;
}
if ($uri ~* /wp\-content/cache/comet\-cache/htmlc/private(?:/|$)) {
  return 403;
}
```

_Just don't put `if` inside a `location{}` block, because `if` is evil inside a `location{}` block._

**Comment by raamdev** [comment]
@jaswsinc Thank you very much for the detailed explanation. I'm going to close this and leave the article as-is. Your comments above are sufficient extra detail for this GitHub issue to address any questions on that topic. 😄

**Comment by pkiula** [comment]
Thank you for this. But this doesn't speak of having a `try_files` directive that points first to a fully static html page, and only if that's not found, to do the usual Wordpress routine of picking up a Comet Cached file. It would be good to have the possibility of having this in Nginx conf: 

    try_files "/wp-content/comet-cache/cache/$host/${uri}.html"   $uri   $uri/ /index.php$is_args$args;


Any guidance on how to compose that would be super. I already know how to NOT use the cache when other file patterns such as `wp-admin` or search are called. Thanks!
